### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by haesleinhuepf** [DorsaRoh/Machine-Learning#1]
Hi @DorsaRoh ,

that's a fantastic repository! I was just wondering under which conditions one could reuse the code and materials provided here, e.g. for teaching my students. Would you mind adding a license file? If you're new to licensing and/or wonder which license to use, you can read more in this blob post: https://focalplane.biologists.com/2023/05/06/if-you-license-it-itll-be-harder-to-steal-it-why-we-should-license-our-work/

Thanks!

Best,
Robert

**Comment by DorsaRoh** [comment]
Hi @haesleinhuepf,

Thanks for the kind words! I’ve added a license to the repo—feel free to use the materials. Let me know if you need anything else! :)

Best,
Dorsa

**Comment by haesleinhuepf** [comment]
Aawesome, thanks!
