### ISSUE TITLE
Vectorized tokens did not capture meaning thus we created embeddings

### ISSUE THREAD

**Issue by JUSTSUJAY** [DorsaRoh/Machine-Learning#2]
In **Tokens** section, a little below transformers

Every token is associated with a vector (some list of numbers)
> encodes the "meaning" of that piece
ex. in considering these vectors as coordinates, words with similar meanings tend to land near each other

I think it would be **incorrect** to say that vectorized tokens[before embeddings were introduced when we used OHE or TF-IDF it didn't capture meaning]

**We can call it the "numerical representation" maybe**

Suggesting because it would help readers learn the importance of embeddings and the reason behind it

If you are okay with contributions I can add the NLP part with tokenization, Lemmetization, and other missing pieces to add depth and create a PR.

**Comment by DorsaRoh** [comment]
Thank you for your thoughtful feedback and suggestions! :)

I completely agree. Please feel free to make suggestions/PRs where you see fit. Your expertise would be valuable!

Thanks again for your input!
